### PR TITLE
Windows compatability

### PR DESCRIPTION
**Pull request by lthiery**
I was trying to get a project to work for Windows and noticed some issues with this crate.

Turns out, prepending apdu serialization with a `0x00` byte fixes Windows and also works on other platforms.

:link: [zboto Link](https://app.clickup.com/t/2karmuz)

### CODE REVIEW

**Comment by lthiery** [comment]
FYI, prefixing a 0x00 byte also requires the buffer to be bigger by one to allow Windows to still fill a full page. If the buffer is not full, Windows pads the buffer with 0's causing corrupted reads from the client.

My most recent commit fixes this.

**Comment by jleni** [comment]
@lthiery Thanks. We are making a lot of changes lately in this library.
Happy to include these too!
It would be important that these modification have a feature flag so are only active in Windows

**Comment by lthiery** [comment]
@jleni I've rebased my changes if this helps land the PR.

**Comment by SionoiS** [comment]
Any news on this?

**Comment by lthiery** [comment]
> Any news on this?

I can do a rebase again if it will be landed. But I'm not sure the maintainers are interested in this 2 year old PR.

**Comment by SionoiS** [comment]
Thanks for figuring this windows compat @lthiery

**Comment by jleni** [comment]
merging into dev to allow CI to run

**Pull request merged**
