### PR TITLE
TCP transport for Ledger's speculos simulator implemented

### PR DESCRIPTION
**Pull request by shufps**
TCP Transport for Ledger's speculos simulator.

### CODE REVIEW

**Comment by jleni** [comment]
This is nice!
I am sorry, I have just merge something before yours and results in a merge conflict. Could you have a look?

By the way, have you look at Zemu? 
This is what we use ourselves. It is a wrapper around speculos that provides many other features (snapshots, control, debugging, etc.).
And there is already a transport for that.

**Comment by shufps** [comment]
Ah, didn't know ZEMU wraps Speculos :)

Hmm, yes well ... Speculos works perfectly with my usual workflow (Eclipse debugging via GDB, Semihosting output, ...) so I'm not sure if I switch before my project is completed :)

But thank you very much for pointing this out! :)

**Comment by jleni** [comment]
Sorry this has been blocked here for long. Let me try to rebase it and see how it goes.

**Comment by shufps** [comment]
Let me clean up a bit first - I'll do another PR when done :)

It was one of the very first rust ever written by me and I would do some things more the uhm rusty way now :)

**Pull request closed without merging**
